# Generated by Django 5.1.3 on 2024-12-02 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='icon',
            new_name='image',
        ),
    ]
