# Generated by Django 5.1.3 on 2024-12-02 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_alter_services_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='features',
        ),
        migrations.AddField(
            model_name='pricing',
            name='color',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pricing',
            name='date',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
