# Generated by Django 5.1.3 on 2024-12-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_remove_pricing_features_pricing_color_pricing_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='button_link',
            new_name='button1_link',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='button_text',
            new_name='button1_text',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='button2_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='button2_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
