# Generated by Django 5.1.3 on 2024-12-02 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_rename_button_link_portfolio_button1_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='button1_link',
        ),
    ]
