# Generated by Django 5.1.3 on 2024-12-02 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_remove_portfolio_button1_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonials',
            name='button_link',
        ),
        migrations.RemoveField(
            model_name='testimonials',
            name='button_text',
        ),
        migrations.AddField(
            model_name='testimonials',
            name='role',
            field=models.CharField(default='Cliente', max_length=20),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='stars',
            field=models.IntegerField(default=0),
        ),
    ]
