# Generated by Django 5.1.3 on 2024-12-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_remove_testimonials_button_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='button_text',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='button_link',
            new_name='media1_url',
        ),
        migrations.AddField(
            model_name='team',
            name='media1_image',
            field=models.ImageField(null=True, upload_to='team/network'),
        ),
        migrations.AddField(
            model_name='team',
            name='media2_image',
            field=models.ImageField(null=True, upload_to='team/network'),
        ),
        migrations.AddField(
            model_name='team',
            name='media2_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='media3_image',
            field=models.ImageField(null=True, upload_to='team/network'),
        ),
        migrations.AddField(
            model_name='team',
            name='media3_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='media4_image',
            field=models.ImageField(null=True, upload_to='team/network'),
        ),
        migrations.AddField(
            model_name='team',
            name='media4_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
