# Generated by Django 5.1.3 on 2024-12-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_remove_contact_address_remove_contact_button_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='altfeatures',
            name='image',
        ),
        migrations.AddField(
            model_name='altfeatures',
            name='icon',
            field=models.CharField(default='xxx', max_length=200),
        ),
    ]
