# Generated by Django 5.1.3 on 2024-12-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_remove_altfeatures_image_altfeatures_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='image',
        ),
        migrations.RemoveField(
            model_name='team',
            name='media1_image',
        ),
        migrations.RemoveField(
            model_name='team',
            name='media2_image',
        ),
        migrations.RemoveField(
            model_name='team',
            name='media3_image',
        ),
        migrations.RemoveField(
            model_name='team',
            name='media4_image',
        ),
        migrations.AddField(
            model_name='pricing',
            name='icon',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='services',
            name='icon',
            field=models.CharField(default='bi bi-cloud-download-fill', max_length=200),
        ),
        migrations.AddField(
            model_name='team',
            name='media1_icon',
            field=models.CharField(default='bi bi-cloud-download-fill', max_length=200),
        ),
        migrations.AddField(
            model_name='team',
            name='media2_icon',
            field=models.CharField(default='bi bi-cloud-download-fill', max_length=200),
        ),
        migrations.AddField(
            model_name='team',
            name='media3_icon',
            field=models.CharField(default='bi bi-cloud-download-fill', max_length=200),
        ),
        migrations.AddField(
            model_name='team',
            name='media4_icon',
            field=models.CharField(default='bi bi-cloud-download-fill', max_length=200),
        ),
        migrations.AlterField(
            model_name='altfeatures',
            name='icon',
            field=models.CharField(default='bi bi-cloud-download-fill', max_length=200),
        ),
    ]
