# Generated by Django 5.1.3 on 2024-12-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0011_remove_services_image_remove_team_media1_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='color',
            field=models.CharField(default='item-cyan', max_length=20),
        ),
    ]
