# Generated by Django 5.1.3 on 2024-12-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0012_services_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='color',
            field=models.CharField(default='cyan', max_length=20),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.TextField(default='Available colors are: \n{ cyan, orange, teal, red, indigo, pink }'),
        ),
    ]
