# Generated by Django 5.1.3 on 2024-12-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0014_portfolio_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter', models.CharField(default='nombre_filtro', max_length=50)),
                ('filter_name', models.CharField(default='Filtro', max_length=50)),
            ],
        ),
    ]
