# Generated by Django 5.1.3 on 2024-12-03 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0015_filter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Filter',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
