# Generated by Django 5.1.3 on 2024-12-03 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0016_delete_filter_delete_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='pinga',
        ),
    ]
