# Generated by Django 5.1.3 on 2024-12-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0017_remove_about_pinga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
