# Generated by Django 5.1.3 on 2024-12-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0019_faq_featureservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='column',
            field=models.BooleanField(default=0),
        ),
    ]
