# Generated by Django 5.1.3 on 2024-12-03 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0020_faq_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='button_link',
        ),
        migrations.AlterField(
            model_name='faq',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='general.services'),
        ),
    ]
