# Generated by Django 5.1.3 on 2024-12-11 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0021_remove_services_button_link_alter_faq_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
