# Generated by Django 5.1.3 on 2024-12-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0022_services_long_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=100)),
                ('budget_type', models.CharField(max_length=10)),
                ('service', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
