# Generated by Django 5.1.3 on 2024-12-03 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter', models.CharField(default='nombre_filtro', max_length=50)),
                ('filter_name', models.CharField(default='Filtro', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('filter', models.CharField(default='app', max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('button1_text', models.CharField(blank=True, max_length=100, null=True)),
                ('button2_text', models.CharField(blank=True, max_length=100, null=True)),
                ('button2_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
