# Generated by Django 5.1.3 on 2024-12-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_featureportfolio_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
