# Generated by Django 5.1.3 on 2024-12-11 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_portfolio_long_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='filter',
        ),
        migrations.AddField(
            model_name='filter',
            name='filter_slug',
            field=models.CharField(db_default='app', default='filter-slug', max_length=50),
        ),
        migrations.AlterField(
            model_name='filter',
            name='filter_name',
            field=models.CharField(default='Nombre Filtro', max_length=50),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.filter'),
        ),
    ]
